name:                notifySend
version:             2019.4.18
github:              "magicloud/notifySend"
license:             BSD3
author:              "Magicloud"
maintainer:          "magiclouds@gmail.com"
copyright:           "None"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            system,desktop

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/magicloud/notifySend#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- dbus

library:
  source-dirs: src
  ghc-options: -Wall
